=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/16_06_2022/es1/Biblioteca.xsd
<?xml version="1.0" ?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="lunghezza_branoType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2}\:[0-5][0-9]"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="branoType"> 
		<xs:sequence> 
			<xs:element name = "titolo_brano" type="xs:string"/>
			<xs:element name="lunghezza_brano" type="lunghezza_branoType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="albumType"> 
		<xs:sequence> 
			<xs:element name = "titolo_album" type="xs:string"/>
			<xs:element name = "anno_pubblicazione" type="xs:integer"/>
			<xs:element name="brano" type="branoType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="musicistaType"> 
		<xs:sequence> 
			<xs:element name = "nome" type="xs:string"/>
			<xs:element name = "cognome" type="xs:string"/>
			<xs:element name = "nome_arte" type="xs:string" minOccurs="0"/>
			<xs:element name = "genere_musicale" type="xs:string"/>
			<xs:element name="album" type="albumType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="bibliotecaType"> 
		<xs:sequence> 
			<xs:element name = "musicista" type="musicistaType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

    <xs:element name="biblioteca" type="bibliotecaType"/>
	
    
</xs:schema>

=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/16_06_2022/es1/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="Biblioteca.xsd">
     <musicista>
          <nome>Alessandro</nome>
          <cognome>Berto</cognome>
          <nome_arte>AleSalo</nome_arte>
          <genere_musicale>Pop</genere_musicale>
          <album>
               <titolo_album>Finally rich</titolo_album>
               <anno_pubblicazione>2012</anno_pubblicazione>
               <brano>
                    <titolo_brano>Love Sosa</titolo_brano>
                    <lunghezza_brano>03:12</lunghezza_brano>
               </brano>
               <brano>
                    <titolo_brano>Hate Bein Sober</titolo_brano>
                    <lunghezza_brano>03:47</lunghezza_brano>
               </brano>
          </album>
          <album>
               <titolo_album>Finally rich remastered</titolo_album>
               <anno_pubblicazione>2022</anno_pubblicazione>
               <brano>
                    <titolo_brano>Love Sosa</titolo_brano>
                    <lunghezza_brano>03:12</lunghezza_brano>
               </brano>
               <brano>
                    <titolo_brano>Hate Bein Sober</titolo_brano>
                    <lunghezza_brano>03:47</lunghezza_brano>
               </brano>
               <brano>
                    <titolo_brano>I don't like</titolo_brano>
                    <lunghezza_brano>04:47</lunghezza_brano>
               </brano>
          </album>
     </musicista>
     <musicista>
          <nome>Alberto</nome>
          <cognome>Bertozzi</cognome>
          <nome_arte>AlbySalo</nome_arte>
          <genere_musicale>Pop</genere_musicale>
          <album>
               <titolo_album>Finally richissimo</titolo_album>
               <anno_pubblicazione>2012</anno_pubblicazione>
               <brano>
                    <titolo_brano>Love Sosa</titolo_brano>
                    <lunghezza_brano>03:12</lunghezza_brano>
               </brano>
               <brano>
                    <titolo_brano>Hate Bein Sober</titolo_brano>
                    <lunghezza_brano>03:47</lunghezza_brano>
               </brano>
          </album>
     </musicista>

</biblioteca>
