=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/14_07_2022/es1/Hotel.xsd
<?xml version="1.0" ?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="password">
		<xs:restriction base="xs:string">
			<xs:length value="8"/>
			<xs:pattern value=".*[0-9].*"/>
			<xs:pattern value=".*[?!*$].*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+\@[^@]+\.[^@]+"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="giudizioType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="eccellente"/>
			<xs:enumeration value="buono"/>
			<xs:enumeration value="medio"/>
			<xs:enumeration value="sufficiente"/>
			<xs:enumeration value="mediocre"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:complexType name="oggettoType">
		<xs:sequence>
			<xs:element name="nome_hotel" type="xs:string"/>
			<xs:element name="fotografia_hotel" type="xs:string"/>
			<xs:element name="giudizio_utenti" type="giudizioType"/>
			<xs:element name="prezzo" type="xs:integer"/>
			<xs:element name="link">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:anyURI">
							<xs:attribute name="cliccato" type="xs:boolean" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="fasciaPrezzoType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="bassa"/>
			<xs:enumeration value="media"/>
			<xs:enumeration value="alta"/>
			<xs:enumeration value="lusso superiore"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="numeroStelleType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="ricercaType"> 
		<xs:sequence> 
			<xs:element name = "e-mail" type="email"/>
			<xs:element name = "password" type="password"/>
			<xs:element name="nazione" type="xs:string"/>
			<xs:element name="citta" type="xs:string"/>
			<xs:element name="numeroStelle" type="numeroStelleType"/>
			<xs:element name="fasciaPrezzo" type="fasciaPrezzoType" minOccurs="0"/>
			<xs:element name="risultato">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="oggetto" type="oggettoType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

    <xs:element name="ricerca" type="ricercaType"/>
	
    
</xs:schema>

=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/14_07_2022/es1/Hotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<ricerca
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="Hotel.xsd">
     <e-mail>alessandrosalomoni56@gmail.com</e-mail>
     <password>pas$w0rd</password>
     <nazione>Italia</nazione>
     <citta>Imola</citta>
     <numeroStelle>3</numeroStelle>
     <fasciaPrezzo>bassa</fasciaPrezzo>
     <risultato>
          <oggetto>
               <nome_hotel>Hotel la bella vita</nome_hotel>
               <fotografia_hotel>image1.jpg</fotografia_hotel>
               <giudizio_utenti>buono</giudizio_utenti>
               <prezzo>45</prezzo>
               <link cliccato="true">https://www.booking.com/</link>
          </oggetto>
          <oggetto>
               <nome_hotel>Hotel la brutta vita</nome_hotel>
               <fotografia_hotel>image2.jpg</fotografia_hotel>
               <giudizio_utenti>eccellente</giudizio_utenti>
               <prezzo>40</prezzo>
               <link cliccato="false">https://www.booking.com/home/</link>
          </oggetto>
     </risultato>
</ricerca>
