=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/23_06_2023/es1/MM.xsd
<?xml version="1.0" ?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="IDType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9]+"/>
		</xs:restriction>
	</xs:simpleType>
	

	<xs:complexType name="queryType"> 
		<xs:sequence> 
			<xs:element name = "inputImageID" type="IDType"/>
			<xs:element name="mod">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="1"/>
						<xs:pattern value="[A-C]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		 	<xs:element name = "cardinality" type="xs:integer"/>
			<xs:element name ="results">
		 		<xs:complexType>
					<xs:sequence>
						<xs:element name="outputImageID" type="IDType" maxOccurs="unbounded"/>
					</xs:sequence>
		 		</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:element name="queries">
  		<xs:complexType>
    		<xs:sequence>
      			<xs:element name="query" type="queryType" maxOccurs="unbounded"/>
    		</xs:sequence>
  		</xs:complexType>
	</xs:element>
	
    
</xs:schema>

=== alesalo03/Materiale_esame_PAW/Materiale_esame/esami/23_06_2023/es1/MM.xml
<?xml version="1.0" encoding="UTF-8"?>
<queries
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="MM.xsd">
    
    <query>
          <inputImageID>image1</inputImageID>
          <mod>B</mod>
          <cardinality>2</cardinality>
          <results>
               <outputImageID>image2</outputImageID>
               <outputImageID>image3</outputImageID>
          </results>
    </query>
     <query>
          <inputImageID>image2</inputImageID>
          <mod>C</mod>
          <cardinality>3</cardinality>
          <results>
               <outputImageID>image4</outputImageID>
               <outputImageID>image3</outputImageID>
               <outputImageID>image5</outputImageID>
          </results>
    </query>

</queries>
