=== alesalo03/Materiale_esame_PAW/Materiale_esame/es1/esercitazione1/Lettera.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--con complexType definisce un tipo complesso (che utilizzerò dopo) con nome corpoType, cioè un elemento che può contenere altri elementi.-->
    <xs:complexType name="corpoType">
    <!--con sequence gli elementi figli devono apparire in questo ordine-->
        <xs:sequence>
            <xs:element name="paragrafo" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="letteraType">
        <xs:sequence>
            <xs:element name="mittente" type="xs:string"/>
            <xs:element name="data" type="xs:date"/>
            <xs:element name="destinatario" type="xs:string"/>
            <xs:element name="oggetto" type="xs:string"/>
            <xs:element name="saluto-cortese" type="xs:string"/>
            <xs:element name="corpo" type="corpoType"/>
            <xs:element name="chiusura" type="xs:string"/>
            <xs:element name="firma" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="lettere">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lettera" type="letteraType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alesalo03/Materiale_esame_PAW/esercitazione1/es1/Lettera.xml
<?xml version="1.0" encoding="UTF-8"?>
<lettere xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../01_PAWeb_solved/Lettera.xsd">
    <lettera>
        <mittente>Alessandro Salomoni</mittente>
        <data>2025-02-27</data>
        <destinatario>Anzelo Jin</destinatario>
        <oggetto>Ti prego segui i corsi coglione</oggetto>
        <saluto-cortese>Buongiornissimo</saluto-cortese>
        <corpo>
            <paragrafo>La prego di venire a lezione signor Jin</paragrafo>
            <paragrafo>Potrebbe anche divertirsi portando con s√® il signor Spada</paragrafo>
        </corpo>
        <chiusura>Arrivederci e a presto</chiusura>
        <firma>Alessandro Salomoni</firma>
    </lettera>
</lettere>
